👋 Challenge introduction.
===
+
== Your assignment.
+
=== _Estimated time: 15 minutes_
* Deploying Applications using the Ansible Automation Platform.

= ☑️ Task 1 - Run the Job Template to deploy applications to the Linux hosts.

Log in to the `Ansible Automation Platform`.

* Select the `Automation Controller` tab at the top of the lab.

Log in using the following credentials: + _Login credentials:_<p> `User:  admin` <p> `Password:  ansible123!` <p>

'''

Click on the `Templates` link under the `Automation Execution` on the left navigation menu.
Launch the `Deploy Application` Job Template by selecting it and clicking on `Launch`, or by simply clicking the `Rocket Launcher` 🚀 icon.

You will be prompted to select the application(s) you want deployed, and to which Linux hosts.

. `Survey` view.
*The default application is `httpd`.
Please add `nginx` to the list of applications to be installed.<p> *For the hosts please add `rhel2` to the default `rhel1` to install applications to both hosts, then click `Next`.<p>
. From the `Review` view.
Observe the details and the extra variables listed below.
Then click `Finish`.

Monitor the job progress.
_This will take a few moments to complete._ The output will list the hosts and the applications that were installed.

= ☑️ Task 2 - Run an adhoc command on rhel1 to confirm that nginx got installed

In this task you will run an adhoc command on `rhel1` and `rhel2` to confirm that `nginx` got installed from the previous application deployment automation job that you just ran.

In the left navigation menus on the left go to the following:  `Automation Execution`, `Infrastructure`, `Inventories`, and select `AWS Inventory`.

Click on the `Hosts` menu, and then click the checkbox next to `rhel1` and `rhel2`.

Once `rhel1` and `rhel2` are selected click on the `Run Command` button.

. `Details` view.
From the `Module` drop down select `service`, and in the `Arguments` field enter the following:  `name=nginx`  Click `Next`.
. `Execution Environment` view.
Select `Default Execution Environment`, then click `Next`.
. `Credential` view.
Select `RHEL on AWS - SSH KEY`, then click `Next`.
. `Review` view.
Click on `Finish`.

This will take just a few moments.
The output will list the hosts and provide details on `nginx`.

In this challenge we covered how you can use automation to deploy applications.
We also walked through how you can perform adhoc commands on target hosts.
There's so much more you can do with Ansible Automation Platform.

'''

*Thank you for taking the time to learn about automating cloud operations tasks (in AWS) using the Red Hat Ansible Automation Platform!
This can easily be performed in other clouds environments too!*

= 🐛 Encountered an issue?

If you have encountered an issue or have noticed something not quite right, please https://github.com/ansible/instruqt/issues/new?title=Issue+with+Ansible+Hybrid+Cloud+Automation+-+Cloud+Operations+(aap2.5)&assignees=hichammourad[open an issue].
